### ISSUE TITLE
Do you offer JSON schema for your product fields?

### ISSUE THREAD

**Issue by emilywwj** [meplato/store2-java-client#12]
So I can mapping our own product fields to yours and create easily. Thanks.

**Comment by olivere** [comment]
We have an OpenAPI-/Swagger-like file to describe the endpoints, if that is of any help to you. It's  in YAML format. I have compressed and attached the file below. HTH.

[products.yaml.zip](https://github.com/meplato/store2-java-client/files/4556716/products.yaml.zip)

**Comment by YSavitski** [comment]
Hi @olivere 
Do you offer OpenAPI-/Swagger documention via any endpoint? May I ask you for sharing up-to-date schema mapping?
Thank you in advance

**Comment by olivere** [comment]
> Hi @olivere Do you offer OpenAPI-/Swagger documention via any endpoint? May I ask you for sharing up-to-date schema mapping? Thank you in advance

Hi @YSavitski! You’re absolutely right: We should watch the dependencies more closely. I’ll reach out to the team.

As for up-to-date OpenAPI specs, while that shouldn’t be necessary if you use the library, we can of course share them with you.

Please give me a day or two. Thank you.
