### ISSUE TITLE
Type 4 Content Integration

### ISSUE THREAD

**Issue by lizhankan** [meplato/store2-java-client#19]
For Type 4 content integration, it is mentioned in the Meplato Store video that item data (incomplete local data) can also be provided with Type 1 static catalog without API.

If so, any idea where I can find a sample for Type 4 static catalog (BMECat or Excel)? Or how to insert a webshop URL into each item in the static catalog?

**Comment by olivere** [comment]
Hi @lizhankan, I forwarded your request to our support channels. I'll keep you posted.

**Comment by DJK0x7BD** [comment]
@lizhankan Hello, for a Type 4 connection it is required to have:

**In Meplato Store At CATALOGUE LEVELS**
* the OCI base URL for the DETAIL_ADD must be set
* "Supports OCI DETAIL_ADD" must be activated in the catalog

At PRODUCT LEVEL (for the configurable articles)
* there must be a named CustomField "isManagedItem" with the value "true
* there must be a named CustomField "managedItemType" with the value "EXTERNAL_SHOP_ITEM
* the externalProductId must not be empty

The configuration on catalog level can only be done via the UI inside Meplato Store. The remaining fields on product level may be configured via Store API or our UI. Using Excel adding the column headers IS_MANAGED_ITEM and EXT_PRODUCT_ID will add two required fields, the remaining field managedItemType will automatically be mapped when detecting all other required fields for a type 4 connection.

The same can be achieved via BMEcat.

<USER_DEFINED_EXTENSIONS>
	<UDX.isManagedItem>true</UDX.isManagedItem>
	<UDX.managedItemType>EXTERNAL_SHOP_ITEM</UDX.managedItemType>
	<UDX.externalProductId>1337</UDX.externalProductId>
</USER_DEFINED_EXTENSIONS>


Minimum requirement
<USER_DEFINED_EXTENSIONS>
	<UDX.WALLMEDIEN.IS_MANAGED_ITEM>true</UDX.WALLMEDIEN.IS_MANAGED_ITEM>
	<UDX.EXT_PRODUCT_ID>1337</UDX.EXT_PRODUCT_ID>
</USER_DEFINED_EXTENSIONS>

**Comment by lizhankan** [comment]
@DJK0x7BD  Thanks so much for your reply.

**Comment by lizhankan** [comment]
@DJK0x7BD 
Regarding the matter above, please could you help with two follow-up questions?
-Is OCI 5.0 required? can we do this with OCI 4.0 too?
-Any chance we can set it up with cXML?
