### ISSUE TITLE
Encoding of SPN for Product GET not working correctly

### ISSUE THREAD

**Issue by manuelbostanci** [meplato/store2-java-client#2]
Try to get product with spn "123456 1+2":
`GET /api/v2/catalogs/CATALOG_ID/work/products/123456+1%2B2`
=> ServiceException (Product not found)

`GET /api/v2/catalogs/CATALOG_ID/work/products/123456+1%252B2` // double url encoded spn
=> WORKS!

**Comment by olivere** [comment]
Thanks for reporting! 👍 We will look into this.

**Comment by olivere** [comment]
Ha! This was a bit more tricky than expected, but we think we got it. We used the chance to modernize the client library (dependencies etc.) and will update the server in sync at the end of the next sprint, which is end of the week. By Monday morning, you should be okay.

If not, please let us know.

Again, thanks for reporting.

**Comment by manuelbostanci** [comment]
Sounds good! ;) Thanks for the quick fix!
