### ISSUE TITLE
Statuscodes not included in ServiceException

### ISSUE THREAD

**Issue by manuelbostanci** [meplato/store2-java-client#3]
Hi guys,
the status code mapping does not work correctly. 
Each ServiceException holds a 0 value for e.getError().getError().getCode().
Would be nice if the correct status code is included in the ServiceException. 
Thank you!

**Comment by olivere** [comment]
Thanks for reporting. We'll have a look.

**Comment by olivere** [comment]
@manuelbostanci Is the code missing for you in any requests, or is it a special API call that won't return the code? I mean, the `getCode` method [is documented as](https://github.com/meplato/store2-java-client/blob/master/src/main/java/com/meplato/store2/Error.java#L82-L89):

```
        /**
         * Returns the error code.
         *
         * @return the error code or 0 if unset.
         */
        public int getCode() {
            return code;
        }
```

... so `0` would be a valid return value. But we could of course fill it with the HTTP status code by default as well.

**Comment by manuelbostanci** [comment]
I've just tested some API calls (Product Get, Product Update, Catalog Publish). They all returned `0` values.
From my point of view it will be good if the error codes by default match the errors described [here](https://developer.meplato.com/store2/rest#errors).
Looks like HTTP status codes ;)

**Comment by daniworm** [comment]
Since the HTTP status code are a documented part of the Meplato REST API and contain important information about what went wrong with a REST API call, that information should also be made available by the store2-java-client. Otherwise you cannot implement error handling specific to the type of error.
So I agree, either always put the HTTP status codes into the ServiceException for any request. Or define local error codes which correspond to the possible HTTP status codes.

**Comment by olivere** [comment]
We agree. And we'll push an update soon which will give you a `getStatusCode()` method on the `ServiceException`. You should use that to check for HTTP status codes in case of an error (HTTP status codes >= 200 and < 300).

For `Error.ErrorInner.getCode()` to work correctly, we will have to update the server side, which will probably happen over the weekend. However, it will basically mirror the HTTP status code (which is what you'll get with `ServiceException.getStatusCode()`).

Thanks for your patience.
