### ISSUE TITLE
Remove value of the field “maximum order quantity” of the product

### ISSUE THREAD

**Issue by iuliiafalkowski** [meplato/store2-java-client#7]
Hi, guys!
can you please answer, how can I remove the value of the field “maximum order quantity” of the product in Meplato Store? The attribute “maximum order quantity” (e.g. in class UpdateProduct --> Double quantityMax) in Meplato Store is marked as optional and can stay empty. 

Suppose, currently for product “A” for the attribute “quantityMax” is set value “10.0”. If I want to change it as: setQuantityMax(0.0), the result will be “0”. If I want to change it as: setQuantityMax(null), the result of attribute will be not changed and stay “10”. 

Question: Is there any possibility to remove the value of the field “maximum order quantity”? What should I set in method setQuantityMax(?) so that the value of the field “maximum order quantity” will remain empty?
Thanks in advance!

**Comment by olivere** [comment]
Hey there! This seems like a bug to me. Congratulations :tada: We're looking at this in the next sprint and I'll let you know.

If you need a workaround, you should be able to use the `ReplaceProduct` endpoint. Notice though that with `ReplaceProduct` you need to pass all product attributes (it replaces all of them) while `UpdateProduct` is a partial update.

**Comment by iuliiafalkowski** [comment]
Thank you for the answer! Can you please tell us when your next sprint will start? The attribute “quantityMax” was just one example. Can you please also check the other attributes of classes UpdateProduct and CreateProduct with types "Integer" and "Double" with similiar behaviour? Thanks in advance!

**Comment by olivere** [comment]
Yes. If this is indeed a bug, it probably includes all nullable fields. Will keep you in the loop.

**Comment by iuliiafalkowski** [comment]
Hi everyone! I wanted to ask if there is any new information according to this bug? Maybe you already know when it approximately will be fixed? Thanks in advance!

**Comment by olivere** [comment]
Hi @iuliiafalkowski. I'm sorry for the late reply. We'll probably deploy a fixed version over the weekend. We'll cut the release on Friday.

**Comment by olivere** [comment]
Good news. If all goes well, we will fix this issue in the weekend release. Sorry for the delay.

**Comment by olivere** [comment]
The new version has been deployed. Let me know if this still fails for you.

**Comment by iuliiafalkowski** [comment]
Hi @olivere ! Thank you for the update! Can you please tell us which value should be set now to the Double and Integer methods in order to remove the old value and leave the field in meplato store empty? I mean for example the field “maximum order quantity”  in meplato store. What should I set to the method setQuantityMax(?) of the class UpdateProduct in order to remove the old value and leave the field in meplato store empty? Are there any documentation available where we can look up such question? Thanks in advance!

**Comment by olivere** [comment]
Hmm... you're right. The team worked on the server-side which didn't respect all three states: valid value, null value, missing value.

But let us think about it. This should be the correct way of handling things, do you agree?

a) If you have a product with e.g. an erroneously set `quantityMax` of `10` and you want to reset that field, you should call `setQuantityMax(null)`. That will serialize like `"quantityMax": null` and therefore reset the value on the server-side.

b) If you have a product with `quantityMax` of `10` and you want to set it to `1000`, you should set call `setQuantityMax(1000.0). That will serialize to `"quantityMax": 1000.0` and therefore set the new value of 1000 on the server-side.

c) If you have a product with `quantityMax` of `10` and you don't want the server to touch it, don't call `setQuantityMax(...)`. That should not serialize `"quantityMax"` at all and the server will not touch it.

I will check now if the client does this correctly.

**Comment by iuliiafalkowski** [comment]
@olivere 
Thank you for the answer! I also think that the behaviour in items a, b and c is correct. I have tested it:

a) If I send the PATCH request according to yout API (https://developer.meplato.com/store2/rest/products/update) 
 'https://{key}:@store.meplato.com/api/v2/catalogs/2352CE227D/work/products/441590?pretty=1' (e.g. with postman tool) with a body: {"quantityMax": null}, so then the old value of the field “maximum order quantity” in meplato store is removed and the field remains empty.

b) But when I try to execute request with Java add set updateProduct.setQuantityMax(null), then the old value of the field “maximum order quantity” in meplato store is not removed.

Thanks in advance!

**Comment by olivere** [comment]
@iuliiafalkowski Yes, I can confirm that. Due to the way Gson works, default values will not be serialized, hence the `setQuantityMax(null)` will not serialize it as `null`. What a shame.

I will work on that now. Good thing is that updates to the client are not as strict as updates to the server, so we see if we can fix things fast.

May I ask which (major) Java version you are using?

**Comment by iuliiafalkowski** [comment]
@olivere  Ok, thank you! We are using Java 8.

**Comment by olivere** [comment]
@iuliiafalkowski Can you try to update to 2.1.8 please? See https://github.com/meplato/store2-java-client/releases/tag/v2.1.8

**Comment by iuliiafalkowski** [comment]
Hi @olivere !

I have updated the new version 2.1.8 and have tested it. The attributes Optional<Double> quantityMax and Optional<Double> quantityMin in class UpdateProduct are working now and the old values of these two fields  in meplato store are removed and remain empty. 

But what about the other Double and Integer attributes in other classes that are also optional? I mean that e.g. the attributes quantityMax  and quantityMin in class CreateProduct are now not implemented with Optional. The other optional Double and Integer attributes that exist in classes UpdatePoduct and CreateProduct that are now not implemented with Optional, are e.g. : 
-priceQty, 
-cuPerOu, 
-leadtime,
-taxRate, 
-netWeight and grossWeight (class Intrastat)
-lbound and price (ScalePrice)

Thanks in advance!

**Comment by olivere** [comment]
Most of the attributes you mentioned are not nullable in our data model. E.g. `priceQty` and `cuPerOu` have a default value of 1, for `taxRate` we have `0.0`. So if you provide a value of `null`, it won't be cleared. You are in control of the value.

The `netWeight` and `grossWeight` fields are part of the `intrastat` struct, same with `scalePrices`. You replace them altogether on the top-level, you don't update individual scale prices or intrastat values.

We will check `leadtime` though.

**Comment by olivere** [comment]
@iuliiafalkowski Thanks for all the discussions around this topic. It's important to get this right.

First, `leadtime` needs to be modified as well. We will update the client to use `Optional<Double>` for `leadtime` as well.

Next, we will change the server side to have the following semantics. I don't think it's a breaking change (which we must prevent in any circumstance):
1. If you don't pass a field in the HTTP request body (as JSON), don't modify it.
2. If you pass a field as `null` in JSON, reset it to its default value. For certain fields the default value literally is `null`, but for some it might mean something different, e.g. a blank string for `cu` or `false` for the `service` flag.
3. If you pass a field as non-`null` in JSON, use that value.

Finally, we will add a chapter to the Developer documentation discussing the semantics of the Update API and give some examples.

**Comment by iuliiafalkowski** [comment]
@olivere 
Thank you for the answer! The suggested semantics find we good. I have one more question about UpsertProduct class, which can be used to create a new product or update an existing product. Will be there the above discussed attributes also changed with Optional?

**Comment by olivere** [comment]
The Upsert API is basically Create if not exists, Replace otherwise. Meaning: You must fill all product fields in `UpsertProduct`. Otherwise the Create call wouldn't work correctly.

**Comment by iuliiafalkowski** [comment]
@olivere 
Thank you for information. Is it already known when approximately the leadtime-changes and the server side changes will become available?

**Comment by iuliiafalkowski** [comment]
Hi @olivere ! I wanted to ask if there is any new information according to this bug? Maybe you already know when approximately the update will be available? Thanks in advance!

**Comment by olivere** [comment]
Hi @iuliiafalkowski. I'm sorry but unfortunately the next deployment is due next weekend. Maybe we can cherry-pick the required changes and apply a hotfix—I will check with the team.

**Comment by iuliiafalkowski** [comment]
@olivere Ok. Thank you!

**Comment by iuliiafalkowski** [comment]
Hi @olivere ! I wanted to ask if the leadtime-changes and the server side changes are already available?

**Comment by olivere** [comment]
Yes, server-side is updated. However, a new version of the client is not released yet.

**Comment by iuliiafalkowski** [comment]
@olivere ok, thank you! Is it already known when approximately the next release will come?

**Comment by olivere** [comment]
Sorry again for the delay. We try to get it out this week.

**Comment by olivere** [comment]
@iuliiafalkowski Can you try [2.1.9](https://github.com/meplato/store2-java-client/releases/tag/v2.1.9)?

**Comment by iuliiafalkowski** [comment]
Hi @olivere! I have tested now a new version with the attributes "cu", "manufacturer" and "leadtime". For the "manufacturer" and "leadtime" everything worked as it was described in this comment:

> 1. If you don't pass a field in the HTTP request body (as JSON), don't modify it.
> 2. If you pass a field as null in JSON, reset it to its default value. For certain fields the default value literally is null, but for some it might mean something different, e.g. a blank string for cu or false for the service flag.
> 3. If you pass a field as non-null in JSON, use that value.

But for "cu" I could not change the value of the attribute even when I set Optional.of(value) . The update was also not working using PATCH request (https://developer.meplato.com/store2/rest/products/update ) .

I also have mentioned that you have changed the properties "name", "price" and "ou" to Optional, although in Meplato Developer Guide (https://developer.meplato.com/store2/rest/products/get) they are marked as manatory. Can these attributes stay empty now?

**Comment by olivere** [comment]
Thanks @iuliiafalkowski. As for `cu`, we have checked that and will do a hotfix today; we were simply missing this field (_meh_).

The DevGuide is correct in that `name`, `price` and `ou` are mandatory. If you pass a default value in mandatory field for the Update API, you should get a validation error (423 IIRC). So, no: They must not be empty.

**Comment by iuliiafalkowski** [comment]
@olivere Thank you! According to mandatory fields: it means that in UpdateProduct, despite the fact that the fields are mandatory in Meplato, they will be marked with Java.Optional, right?

**Comment by olivere** [comment]
Yes, we've changed them to be like that. It's not 100% correct as we don't have cases 1-3 you mentioned above (case 2 will result in a validation error). We have still decided to do so to prepare for future changes that might make these fields optional.

**Comment by olivere** [comment]
Closed for inactivity.
